# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/Wines.proto for package 'wineskills_rpc'

require 'grpc'
require 'protos/Wines_pb'

module WineskillsRpc
  module Wines
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'wineskills_rpc.Wines'

      rpc :GetWines, ::WineskillsRpc::GetWinesRequest, ::WineskillsRpc::GetWinesResponse
    end

    Stub = Service.rpc_stub_class
  end
end
