# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/Wines.proto

require 'google/protobuf'


descriptor_data = "\n\x12protos/Wines.proto\x12\x0ewineskills_rpc\"\x11\n\x0fGetWinesRequest\"7\n\x10GetWinesResponse\x12#\n\x05wines\x18\x01 \x03(\x0b\x32\x14.wineskills_rpc.Wine\"\x14\n\x04Wine\x12\x0c\n\x04name\x18\x01 \x01(\t2X\n\x05Wines\x12O\n\x08GetWines\x12\x1f.wineskills_rpc.GetWinesRequest\x1a .wineskills_rpc.GetWinesResponse\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module WineskillsRpc
  GetWinesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wineskills_rpc.GetWinesRequest").msgclass
  GetWinesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wineskills_rpc.GetWinesResponse").msgclass
  Wine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wineskills_rpc.Wine").msgclass
end
